### ISSUE TITLE
Recommended software environment for building October toolchain ?

### ISSUE THREAD

**Issue by mward15** [ucb-bar/fpga-zynq#37]
Last weekends I tried again building riscv-gnu-toolchain using fpga-zynq which is linked to October version of rocket-chip @ 5392219 , with the following software configurations:
1) CentOS 6.8 with devtoolset-2 which provides gcc 4.8.2 to CentOS 6.8
2) Fedora 25 with gcc 6.2.1

Both builds are failing, probably because CentOS 6.8 is too old and Fedora 25 is too new for building this toolchain (maybe it treats some earlier warnings as errors...)
**Please tell, what software configuration are you using?**
[*] Linux distribution, its version number and architecture? (i386 or x86_64)
[*] version of gcc?
This information will be very helpful, because the official readme says that any gcc >4.8 is OK, but sadly it isn't...

**Comment by davidbiancolin** [comment]
Since you ask: Ubuntu, 14.04, x86_64. GCC 4.8.4. 

This repository really only builds a thin shell around software hosted in other RISC-V repositories. The README would be perhaps more apt in saying that "Building the RISCV toolchain and FESVR are prerequisites for using this repository".  

If there are problems that arise directly from the compilation of source hosted here, i'd be happy to fix them, otherwise you might wish to take this up with the people that look after the toolchain.
